# Generated by Django 4.1.9 on 2023-05-29 09:25

from django.db import migrations, models
import dojo.models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0185_product_disable_sla_breach_notifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=2000)),
                ('template_format', models.CharField(max_length=80, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=dojo.models.UniqueUploadNameProvider('report_templates', keep_basename=True))),
            ],
        ),
    ]
